### PR TITLE
Mmap experiments

### LINKED ISSUE #8: Back `MerkleTree::data` with `mmap`
The complication is that the `memmap::MmapMut` solution we normally use only covers the `u8` type whereas `MerkleTree::data` is a `Vec<T>` where `T: Ord + Clone + AsRef<[u8]> + Sync + Send`. See https://github.com/filecoin-project/merkle_light/pull/7 as an example of a failed solution.

As suggested by dig these are the current steps to investigate a more elaborate implementation:

> because `T` has `AsRef<[u8]>` you need to rely on that
you need to change the method to require two things
a) having the data amount known before hand
b) having the size of `T` in bytes known
then you can create an mmap large enough to hold the things
get it as a `&mut [u8]`
and then use https://docs.rs/rayon/1.0.2/rayon/slice/trait.ParallelSliceMut.html#method.par_chunks_mut to write into each chunk the hash

### PR DESCRIPTION
**Pull request by dignifiedquire**
- abstract underlying storage into a trait
- add required trait features on the `T` elements that are stored in the tree
- implement backing store using `Vec` and `Mmap`
- add `from_byte_slice` for efficient creation if the leafs already exist as a consecutive buffer

Warning: Very crude code. 

- Drawbacks
  - additional restrictions for `T`
  - currently not super efficient, but could be made so I believe
  - can not implement `Deref` when using mmap store, I don't think that is a critical feature though

Closes #8.

### CODE REVIEW

File: merkle/src/merkle.rs [hunk 1]
```diff
@@ -37,21 +39,204 @@ use std::ops;
...
+    store: MmapMut,
+    len: usize,
+    _e: PhantomData<E>,
+}
+
+impl<E: Element> ops::Deref for MmapStore<E> {
+    type Target = [E];
+
+    fn deref(&self) -> &Self::Target {
+        unimplemented!()
```
Comment (schomatis) [inline merkle/src/merkle.rs]: @dignifiedquire This is conversion that stopped me short initially and I need to resolve it to test the `mmap` version, how should this be implemented? I've noticed that you tried to avoid `mem::transmute` which I originally thought of in https://github.com/filecoin-project/merkle_light/issues/8#issuecomment-468829569, but I can't think of any alternatives at the moment, WDYT?

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: what is the code path that relies on this? I am not sure we can actually implement it correctly

Comment (schomatis) [reply merkle/src/merkle.rs]: https://circleci.com/gh/filecoin-project/rust-fil-proofs/15226?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: can you try running these with `RUST_BACKTRACE=1` so we can see where this originates from?

Comment (schomatis) [reply merkle/src/merkle.rs]: https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/src/drgporep.rs#L273

and related.

Just so I follow your thought process in the design, was the `unimplemented` macro left there intentionally? If so, why was the deref implemented for the rest of the structures? (e.g., `MerkleTree`, `VecStore`) Should we avoid using `transmute`?

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: - yes, we should avoid transmute if at all possible (it leads down a dark path of unsafety)
- I left it in there to be able to reuse existing tests, but otherwise I think that we should try to avoid relying on deref if we can

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: it should be easy to just use the read methods for the linked code instead

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: hmm, maybe not that straight forward, this is tricky

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: we could easily support `AsRef<[u8]>` without being unsafe, maybe that could help us in that case?

Comment (schomatis) [reply merkle/src/merkle.rs]: > we could easily support `AsRef<[u8]>` without being unsafe, maybe that could help us in that case?

Would that be for the entire tree or each element independently? (the `AsRef<[u8]>` support)

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: I meant for the entire tree

Comment (schomatis) [reply merkle/src/merkle.rs]: I think that may work, but how do we implement something like that for the entire tree without unsafe things like `transmute`? That was what blocked me in the first place, the `[T] <-> [u8]` conversion (as originally described in https://github.com/filecoin-project/merkle_light/issues/8).

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: well the mmap already gives you `&[u8]` for free, so the hard part in this case is getting it done for the vector, which....hmmmm is hard to say the least as even a transmute would give you the wrong thing likely

Comment (dignifiedquire) [reply merkle/src/merkle.rs]: I think we need to figure out a different api to do those accesses we do in fil-proofs, that we can support with both backing stores

Comment (schomatis) [reply merkle/src/merkle.rs]: Ok, I'll see what can be done on the `rust-fil-proofs` side to simplify and standardize a bit more how we access the tree.

**Comment by dignifiedquire** [comment]
@schomatis can you please make sure that CI is passing again?

**Comment by schomatis** [comment]
> @schomatis can you please make sure that CI is passing again?

@dignifiedquire again? when did it ever passed? see https://github.com/filecoin-project/merkle_light/issues/11 and https://github.com/filecoin-project/merkle_light/pull/10
